### PR TITLE
Fix issue #35: Make y_max work in autoplot

### LINKED ISSUE #35: The y_max parameter to autoplot is ignored
### Description

Setting the y_max parameter does not affect the plot generated by autoplot.microbenchmark. The issue is caused by coord_flip reverting parameters already passed to coord_cartesian.

### Expected behavior

Providing a value for y_max should produce a plot where the time scale goes from 0 to y_max.

### Minimal, reproducible example

```r
library(ggplot2)
library(microbenchmark)

# dummy data
set.seed(1)
res <- data.frame(
  expr = factor(c("a", "b", "c")[rep(1:3, 10)]),
  time = 1e6 + exp(10+rnorm(3000))
)
class(res) <- c("microbenchmark", class(res))

# this plot should go from 0 to 1.5, but it does the same as without y_max
autoplot(res, y_max = 1.5)
```

### Session Info

```r
R version 4.2.0 (2022-04-22 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=Norwegian Nynorsk_Norway.utf8  LC_CTYPE=Norwegian Nynorsk_Norway.utf8    LC_MONETARY=Norwegian Nynorsk_Norway.utf8
[4] LC_NUMERIC=C                              LC_TIME=Norwegian Nynorsk_Norway.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] microbenchmark_1.4.9 ggplot2_3.3.6       

loaded via a namespace (and not attached):
 [1] rstudioapi_0.13  magrittr_2.0.3   tidyselect_1.1.2 munsell_0.5.0    colorspace_2.0-3 R6_2.5.1         rlang_1.0.4     
 [8] fansi_1.0.3      dplyr_1.0.9      tools_4.2.0      grid_4.2.0       gtable_0.3.0     utf8_1.2.2       cli_3.3.0       
[15] DBI_1.1.3        withr_2.5.0      ellipsis_0.3.2   digest_0.6.29    assertthat_0.2.1 tibble_3.1.7     lifecycle_1.0.1 
[22] farver_2.1.1     purrr_0.3.4      vctrs_0.4.1      glue_1.6.2       labeling_0.4.2   compiler_4.2.0   pillar_1.8.0    
[29] generics_0.1.3   scales_1.2.0     lubridate_1.8.0  pkgconfig_2.0.3 
```

### PR DESCRIPTION
**Pull request by tinygreen**
The y_max parameter in autoplot.microbenchmark is currently ignored, because coord_flip cancels out the previous call to coord_cartesian. Also, coord_cartesian is redundant, as its ylim argument can be passed to coord_flip instead.

Now that y_max works, two issues appear in how it works: First, y_min cannot be 0 on a log axis, so I use the minimum value from object$ntime when log == TRUE. Second, the default value for y_max is derived from object$time, while the plot uses object$ntime, so I replaced the default with NULL and calculate the default value after calculating object$ntime. Note that the previous default for y_max also had no effect. This is why I did not keep the 1.05 factor, as it would change the behaviour compared to before.

Calling the function without y_max produces the same plots as before, but without the warning from coord_flip that it is replacing the coordinate system from coord_cartesian.

Fixes #35.

### CODE REVIEW

File: R/autoplot.R [hunk 1]
```diff
@@ -23,21 +23,24 @@
...
 autoplot.microbenchmark <- function(object, ...,
                                     log=TRUE,
-                                    y_max=1.05 * max(object$time)) {
+                                    y_max=NULL) {
   if (!requireNamespace("ggplot2"))
     stop("Missing package 'ggplot2'.")
   y_min <- 0
   object$ntime <- convert_to_unit(object$time, "t")
+  if (is.null(y_max)) {
+    y_max <- max(object$ntime)
```
Comment (joshuaulrich) [inline R/autoplot.R:32]: Is there a reason you removed the 1.05 multiplier that was the default?

**Review by joshuaulrich — COMMENTED** [review]
One question, otherwise lgtm

File: R/autoplot.R (hunk 1 above)
Comment (tinygreen) [reply R/autoplot.R:32]: I mentioned it in the cm, but I should have explained it better. The multiplier had no effect, as coord_flip() was called without ylim and therefore used the ggplot default, which is the range of values without any multiplier: `ylim = range(object$ntime)`. Ggplot uses some padding between the "active" plot area and the frame anyway. So the bottom line is that _not_ removing the multiplier would change the behaviour of autoplot.microbenchmark (add more padding than before) when called without any parameters other than `object`.

Comment (joshuaulrich) [reply R/autoplot.R:32]: Got it. Thanks for (re-)explaining!

**Review by joshuaulrich — APPROVED** [review]
ltgm

**Comment by joshuaulrich** [comment]
Thanks for the great report and PR!
